"""initial_schema

Revision ID: 140ec83bcd4a
Revises: 
Create Date: 2026-05-19 16:12:58.476734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '140ec83bcd4a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('mlbam_team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('abbreviation', sa.String(length=5), nullable=False),
    sa.Column('league', sa.String(length=5), nullable=False),
    sa.Column('division', sa.String(length=20), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('venue_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('mlbam_team_id')
    )
    op.create_table('players',
    sa.Column('mlbam_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=5), nullable=False),
    sa.Column('bats', sa.String(length=1), nullable=True),
    sa.Column('throws', sa.String(length=1), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_team_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['current_team_id'], ['teams.mlbam_team_id'], ),
    sa.PrimaryKeyConstraint('mlbam_id')
    )
    op.create_table('team_daily_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('last10_wins', sa.Integer(), nullable=True),
    sa.Column('last10_losses', sa.Integer(), nullable=True),
    sa.Column('last10_win_rate', sa.Float(), nullable=True),
    sa.Column('home_wins', sa.Integer(), nullable=True),
    sa.Column('home_losses', sa.Integer(), nullable=True),
    sa.Column('runs_scored', sa.Integer(), nullable=True),
    sa.Column('runs_allowed', sa.Integer(), nullable=True),
    sa.Column('pythagenpat_wp', sa.Float(), nullable=True),
    sa.Column('streak_signed', sa.Integer(), nullable=True),
    sa.Column('rest_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.mlbam_team_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('game_pk', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('game_datetime', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('venue_name', sa.String(length=100), nullable=True),
    sa.Column('is_dome', sa.Boolean(), nullable=True),
    sa.Column('home_starter_id', sa.Integer(), nullable=True),
    sa.Column('away_starter_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['away_starter_id'], ['players.mlbam_id'], ),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.mlbam_team_id'], ),
    sa.ForeignKeyConstraint(['home_starter_id'], ['players.mlbam_id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.mlbam_team_id'], ),
    sa.PrimaryKeyConstraint('game_pk')
    )
    op.create_index(op.f('ix_games_game_date'), 'games', ['game_date'], unique=False)
    op.create_table('player_season_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('era', sa.Float(), nullable=True),
    sa.Column('fip', sa.Float(), nullable=True),
    sa.Column('xfip', sa.Float(), nullable=True),
    sa.Column('whip', sa.Float(), nullable=True),
    sa.Column('k_pct', sa.Float(), nullable=True),
    sa.Column('bb_pct', sa.Float(), nullable=True),
    sa.Column('hr9', sa.Float(), nullable=True),
    sa.Column('innings_pitched', sa.Float(), nullable=True),
    sa.Column('wrc_plus', sa.Float(), nullable=True),
    sa.Column('ops', sa.Float(), nullable=True),
    sa.Column('babip', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.mlbam_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_statcast_summary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('xwoba', sa.Float(), nullable=True),
    sa.Column('barrel_rate', sa.Float(), nullable=True),
    sa.Column('hard_hit_pct', sa.Float(), nullable=True),
    sa.Column('chase_rate', sa.Float(), nullable=True),
    sa.Column('swstr_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.mlbam_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('batter_game_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_pk', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('ab', sa.Integer(), nullable=True),
    sa.Column('h', sa.Integer(), nullable=True),
    sa.Column('hr', sa.Integer(), nullable=True),
    sa.Column('rbi', sa.Integer(), nullable=True),
    sa.Column('bb', sa.Integer(), nullable=True),
    sa.Column('k', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['game_pk'], ['games.game_pk'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.mlbam_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.mlbam_team_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batter_game_logs_game_date'), 'batter_game_logs', ['game_date'], unique=False)
    op.create_table('game_lineups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_pk', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('batting_order', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=5), nullable=True),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['game_pk'], ['games.game_pk'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.mlbam_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.mlbam_team_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_pk', sa.Integer(), nullable=False),
    sa.Column('prediction_date', sa.Date(), nullable=False),
    sa.Column('home_win_prob', sa.Float(), nullable=False),
    sa.Column('away_win_prob', sa.Float(), nullable=False),
    sa.Column('confidence_level', sa.String(length=5), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('lgbm_prob', sa.Float(), nullable=True),
    sa.Column('xgb_prob', sa.Float(), nullable=True),
    sa.Column('shap_top5', sa.JSON(), nullable=True),
    sa.Column('reasoning_text', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['game_pk'], ['games.game_pk'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_pk')
    )
    op.create_index(op.f('ix_game_predictions_prediction_date'), 'game_predictions', ['prediction_date'], unique=False)
    op.create_table('game_weather',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_pk', sa.Integer(), nullable=False),
    sa.Column('temp_f', sa.Float(), nullable=True),
    sa.Column('wind_speed_mph', sa.Float(), nullable=True),
    sa.Column('wind_dir', sa.String(length=10), nullable=True),
    sa.Column('precip_mm', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['game_pk'], ['games.game_pk'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pitcher_game_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_pk', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('is_starter', sa.Boolean(), nullable=True),
    sa.Column('ip', sa.Float(), nullable=True),
    sa.Column('er', sa.Integer(), nullable=True),
    sa.Column('k', sa.Integer(), nullable=True),
    sa.Column('bb', sa.Integer(), nullable=True),
    sa.Column('h', sa.Integer(), nullable=True),
    sa.Column('hr', sa.Integer(), nullable=True),
    sa.Column('pitches', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['game_pk'], ['games.game_pk'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.mlbam_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.mlbam_team_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pitcher_game_logs_game_date'), 'pitcher_game_logs', ['game_date'], unique=False)
    op.create_table('statcast_pitches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('game_pk', sa.Integer(), nullable=True),
    sa.Column('pitcher_id', sa.Integer(), nullable=True),
    sa.Column('batter_id', sa.Integer(), nullable=True),
    sa.Column('pitcher_team_id', sa.Integer(), nullable=True),
    sa.Column('batter_team_id', sa.Integer(), nullable=True),
    sa.Column('pitch_type', sa.String(length=5), nullable=True),
    sa.Column('release_speed', sa.Float(), nullable=True),
    sa.Column('spin_rate', sa.Float(), nullable=True),
    sa.Column('launch_speed', sa.Float(), nullable=True),
    sa.Column('launch_angle', sa.Float(), nullable=True),
    sa.Column('is_hard_hit', sa.Boolean(), nullable=True),
    sa.Column('is_barrel', sa.Boolean(), nullable=True),
    sa.Column('events', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('swing', sa.Boolean(), nullable=True),
    sa.Column('whiff', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['batter_id'], ['players.mlbam_id'], ),
    sa.ForeignKeyConstraint(['batter_team_id'], ['teams.mlbam_team_id'], ),
    sa.ForeignKeyConstraint(['game_pk'], ['games.game_pk'], ),
    sa.ForeignKeyConstraint(['pitcher_id'], ['players.mlbam_id'], ),
    sa.ForeignKeyConstraint(['pitcher_team_id'], ['teams.mlbam_team_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statcast_pitches_game_date'), 'statcast_pitches', ['game_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statcast_pitches_game_date'), table_name='statcast_pitches')
    op.drop_table('statcast_pitches')
    op.drop_index(op.f('ix_pitcher_game_logs_game_date'), table_name='pitcher_game_logs')
    op.drop_table('pitcher_game_logs')
    op.drop_table('game_weather')
    op.drop_index(op.f('ix_game_predictions_prediction_date'), table_name='game_predictions')
    op.drop_table('game_predictions')
    op.drop_table('game_lineups')
    op.drop_index(op.f('ix_batter_game_logs_game_date'), table_name='batter_game_logs')
    op.drop_table('batter_game_logs')
    op.drop_table('player_statcast_summary')
    op.drop_table('player_season_stats')
    op.drop_index(op.f('ix_games_game_date'), table_name='games')
    op.drop_table('games')
    op.drop_table('team_daily_snapshots')
    op.drop_table('players')
    op.drop_table('teams')
    # ### end Alembic commands ###
