"""add_game_date_to_lineups_and_xwoba_to_statcast

Revision ID: 4fb0b416e598
Revises: 140ec83bcd4a
Create Date: 2026-05-19 17:00:05.190437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fb0b416e598'
down_revision: Union[str, Sequence[str], None] = '140ec83bcd4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_lineups', sa.Column('game_date', sa.Date(), nullable=False))
    op.create_index(op.f('ix_game_lineups_game_date'), 'game_lineups', ['game_date'], unique=False)
    op.add_column('statcast_pitches', sa.Column('xwoba', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statcast_pitches', 'xwoba')
    op.drop_index(op.f('ix_game_lineups_game_date'), table_name='game_lineups')
    op.drop_column('game_lineups', 'game_date')
    # ### end Alembic commands ###
